resolver: lts-8.13

packages:
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test

extra-deps:
- snappy-framing-0.1.1
- snappy-0.2.0.2
